// File generated by flutterfire_cli.
// This file should be committed to version control but not included in binary distributions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVxkPakT0z5KNGipKItE_aB8yerVCX5zM',
    appId: '1:857124835418:web:b806e0b456b09ffdecc863',
    messagingSenderId: '857124835418',
    projectId: 'smart-car-tracker-test1',
    authDomain: 'smart-car-tracker-test1.firebaseapp.com',
    databaseURL: 'https://smart-car-tracker-test1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-car-tracker-test1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxkPakT0z5KNGipKItE_aB8yerVCX5zM',
    appId: '1:857124835418:web:b806e0b456b09ffdecc863',
    messagingSenderId: '857124835418',
    projectId: 'smart-car-tracker-test1',
    authDomain: 'smart-car-tracker-test1.firebaseapp.com',
    databaseURL: 'https://smart-car-tracker-test1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-car-tracker-test1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTzmFzuyI53AX3bMZrJLUp99OYTYGmHus',
    appId: '1:857124835418:android:6416744d04b594b4ecc863',
    messagingSenderId: '857124835418',
    projectId: 'smart-car-tracker-test1',
    databaseURL: 'https://smart-car-tracker-test1-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVxkPakT0z5KNGipKItE_aB8yerVCX5zM',
    appId: '1:857124835418:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '857124835418',
    projectId: 'smart-car-tracker-test1',
    databaseURL: 'https://smart-car-tracker-test1-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.example.smartCarTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVxkPakT0z5KNGipKItE_aB8yerVCX5zM',
    appId: '1:857124835418:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '857124835418',
    projectId: 'smart-car-tracker-test1',
    databaseURL: 'https://smart-car-tracker-test1-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.example.smartCarTracker',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBVxkPakT0z5KNGipKItE_aB8yerVCX5zM',
    appId: '1:857124835418:web:b806e0b456b09ffdecc863',
    messagingSenderId: '857124835418',
    projectId: 'smart-car-tracker-test1',
    authDomain: 'smart-car-tracker-test1.firebaseapp.com',
    databaseURL: 'https://smart-car-tracker-test1-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
